source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MGKalman_Example', :exclusive => true do
  pod "MGKalman", :path => "../"
end

target 'MGKalman_Tests', :exclusive => true do
  pod "MGKalman", :path => "../"

  
end
